services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - msa-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - msa-network

  mysqlchatbot:
    platform: linux/amd64
    container_name: mysqlchatbot
    image: mysql:latest
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=chat_history
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3


  mysql-mydata:
    platform: linux/amd64
    container_name: mysql-mydata
    image: jayiuk/mydata:6th
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=mydata
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - mysql-mydata-data:/var/lib/mysql

  mysql-loan:
    platform: linux/amd64
    container_name: mysql-loan
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=loan_service
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql-user:
    platform: linux/amd64
    container_name: mysql-user
    image: mysql:latest
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user_service
#    volumes:
#      - mysql-user-data:/var/lib/mysql
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql-loan-group:
    platform: linux/amd64
    container_name: mysql-loan-group
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=loan_group_service
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-invest:
    platform: linux/amd64
    container_name: postgres-invest
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=joyeeun
      - POSTGRES_PASSWORD=dPdmsdk?0928
      - POSTGRES_DB=investment_service
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U joyeeun -d investment_service" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-repayment:
    platform: linux/amd64
    container_name: postgres-repayment
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=joyeeun
      - POSTGRES_PASSWORD=dPdmsdk?0928
      - POSTGRES_DB=repayment_service
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U joyeeun -d repayment_service" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    platform: linux/amd64
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - msa-network


  gateway-service:
    platform: linux/amd64
    container_name: gateway-service
    image: sooook/gateway-service:latest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - msa-network
    depends_on:
      eureka-service:
        condition: service_started
      loan-service:
        condition: service_started
      loan-group-service:
        condition: service_started
      user-service:
        condition: service_started
      invest-service:
        condition: service_started
      repayment-service:
        condition: service_started

  eureka-service:
    platform: linux/amd64
    container_name: eureka-service
    image: sooook/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - msa-network
#    healthcheck:
#      test: ["CMD", "wget", "--spider", "http://localhost:8761/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  loan-service:
    container_name: loan-service
    platform: linux/amd64
    image: sooook/loan-service:test
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-loan:3306/loan_service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=docker
      - LOAN_GROUP_SERVICE_URL=http://loan-group-service:8084
      - USER_SERVICE_URL=http://user-service:8085
      - INVEST_SERVICE_URL=http://invest-service:8081
      - REPAYMENT_SERVICE_URL=http://repayment-service:8082
    #      - LOAN_SERVICE_URL=http://loan-service:8083
    networks:
      - msa-network
    depends_on:
      mysql-loan:
        condition: service_healthy
      eureka-service:
        condition: service_started

  user-service:
    container_name: user-service
    platform: linux/amd64
    image: sooook/user-service:test
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/user_service?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=docker
      - LOAN_GROUP_SERVICE_URL=http://loan-group-service:8084
      #      - USER_SERVICE_URL=http://user-service:8085
      - INVEST_SERVICE_URL=http://invest-service:8081
      - REPAYMENT_SERVICE_URL=http://repayment-service:8082
      - LOAN_SERVICE_URL=http://loan-service:8083
    networks:
      - msa-network
    depends_on:
      mysql-user:
        condition: service_healthy
      eureka-service:
        condition: service_started
      redis:
        condition: service_started

  loan-group-service:
    container_name: loan-group-service
    platform: linux/amd64
    image: sooook/loan-group-service:test
    restart: on-failure
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-loan-group:3306/loan_group_service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=docker
      #      - LOAN_GROUP_SERVICE_URL=http://loan-group-service:8084
      - USER_SERVICE_URL=http://user-service:8085
      - INVEST_SERVICE_URL=http://invest-service:8081
      - REPAYMENT_SERVICE_URL=http://repayment-service:8082
      - LOAN_SERVICE_URL=http://loan-service:8083
    networks:
      - msa-network
    depends_on:
      mysql-loan-group:
        condition: service_healthy
      eureka-service:
        condition: service_started
      redis:
        condition: service_started

  invest-service:
    container_name: invest-service
    platform: linux/amd64
    image: sooook/invest-service:test
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-invest:5432/investment_service
      - SPRING_DATASOURCE_USERNAME=joyeeun
      - SPRING_DATASOURCE_PASSWORD=dPdmsdk?0928
      - SPRING_PROFILES_ACTIVE=docker
      - LOAN_GROUP_SERVICE_URL=http://loan-group-service:8084
      - USER_SERVICE_URL=http://user-service:8085
      #      - INVEST_SERVICE_URL=http://invest-service:8081
      - REPAYMENT_SERVICE_URL=http://repayment-service:8082
      - LOAN_SERVICE_URL=http://loan-service:8083
    networks:
      - msa-network
    depends_on:
      postgres-invest:
        condition: service_healthy
      eureka-service:
        condition: service_started

  repayment-service:
    container_name: repayment-service
    platform: linux/amd64
    image: sooook/repayment-service:test
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-repayment:5432/repayment_service
      - SPRING_DATASOURCE_USERNAME=joyeeun
      - SPRING_DATASOURCE_PASSWORD=dPdmsdk?0928
      - SPRING_PROFILES_ACTIVE=docker
      - LOAN_GROUP_SERVICE_URL=http://loan-group-service:8084
      - USER_SERVICE_URL=http://user-service:8085
      - INVEST_SERVICE_URL=http://invest-service:8081
      #      - REPAYMENT_SERVICE_URL=http://repayment-service:8082
      - LOAN_SERVICE_URL=http://loan-service:8083
    networks:
      - msa-network
    depends_on:
      postgres-repayment:
        condition: service_healthy
      eureka-service:
        condition: service_started

  chatbot-proxy:
    container_name: chatbot-proxy
    platform: linux/amd64
    image: sooook/chatbot-proxy-service:latest
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - CHATBOT_SERVER_URL=http://chatbot-service:8000
    networks:
      - msa-network
    depends_on:
      eureka-service:
        condition: service_started

  chatbot-service: # Python 챗봇 서버
    container_name: chatbot-service
    platform: linux/amd64
    image: jayiuk/chatbot:15th
    ports:
      - "8000:8000"
    networks:
      - msa-network

  pdf-service:
    container_name: pdf-service
    platform: linux/amd64
    image: jayiuk/screeninginput:12th
    ports:
      - "4000:4000"
    networks:
      - msa-network
    env_file:
      - .env

  credit-proxy:
    container_name: credit-service-proxy
    platform: linux/amd64
    image: sooook/credit-proxy-service:latest
    environment:
      - SERVICES_PDF_EXTRACTOR_URL=http://pdf-service:4000
      - SERVICES_CREDIT_MODEL_URL=http://credit-service:80 # 포트번호 바꿔야할수 있음
      - SPRING_PROFILES_ACTIVE=docker
      - USER_SERVICE_URL=http://user-service:8085
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-mydata:3306/mydata?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "8090:8090"
    networks:
      - msa-network
    depends_on:
      mysql-user:
        condition: service_healthy


  credit-service:
    container_name: credit-service
    platform: linux/amd64
    image: jijoungee/fastapi-monitoring:3st
    ports:
      - "80:80"
    networks:
      - msa-network

  chatbot-service-non: # Python 챗봇 서버
    container_name: chatbot-service-non
    platform: linux/amd64
    image: jayiuk/nologin:6th
    ports:
      - "8070:8070"
    networks:
      - msa-network

volumes:
  mysql-mydata-data:

networks:
  msa-network:
    driver: bridge
    attachable: true