spring:
  datasource:
    url: jdbc:mysql:///localhost:3308/loan_group_service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  redis:
    host: redis
    port: 6379

  application:
    name: loan-group-service

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #register-with-eureka: true
    #fetch-registry: true

logging:
  level:
    com:
      billit: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

