spring:
  datasource:
    url: jdbc:mysql://localhost:3308/loan_group_service
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  application:
    name: loan-group
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8084
