spring:
  datasource:
    url: jdbc:mysql://localhost:3308/loan_group_service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  application:
    name: loan-group-service

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


feign:
  client:
    config:
      loan-group-service:
        url: ${LOAN_GROUP_SERVICE_URL:http://host.docker.internal:8084}
      invest-service:
        url: ${INVEST_SERVICE_URL:http://host.docker.internal:8081}
      repayment-service:
        url: ${REPAYMENT_SERVICE_URL:http://host.docker.internal:8082}
      loan-service:
        url: ${LOAN_SERVICE_URL:http://host.docker.internal:8083}
      user-service:
        url: ${USER_SERVICE_URL:http://host.docker.internal:8085}

logging:
  level:
    com:
      billit: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

